baseURL = 'https://algerian-lang.org'  # Your domain name.
languageCode = 'en-US'
title = 'Algerian-lang.org'  # Title of your website

[params]
  github = 'https://github.com/algerian-lang-org'
  username = 'algerian-lang-org'

  # To enable giscus, the GitHub-discussions-based comment section,
  # input the repository for the discussions below. For more details, see
  # https://giscus.app
[params.giscus]
  repo = 'algerian-lang-org/algerian-lang-org.github.io'
  repoId = 'R_kgDON9fIMw'
  category = 'Blog comments'
  categoryId = 'DIC_kwDON9fIM84CnuS3'
  mapping = 'pathname'
  reactionsEnabled = '1'
  inputPosition = 'bottom'
  theme = 'light'
  lang = 'en'

[pagination]
  pagerSize = 5  # Specify the max number of rows to be returned in list

# Menu items displayed in the header.
[[menus.main]]
  name = 'Contact'
  url = 'mailto:contact@algerian-lang.org'
  weight = 1
[[menus.main]]
  name = 'About'
  url = '/about'
  weight = 2

[[module.imports]]
  path = "github.com/discaptive/hugo-discaptive"

